# This is a sample build configuration for GitHub Actions

name: Build

on:
  pull_request:
    inputs:
      build_mac:
        description: 'Set to true to build for Mac'
        required: false
        default: 'false'

jobs:
  mac:
    if: ${{ (github.event_name == 'pull_request' && github.repository == 'Starfallan/PiliNara') || github.event.inputs.build_mac == 'true' }}
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build
        run: echo "Building for macOS..."

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build
        run: echo "Building for Linux..."